local_costmap:
  update_frequency: 20
  publish_frequency: 20
  transform_tolerance: 0.4
  static_map: true
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.2
  inflation_radius: 3.85
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
