TrajectoryPlannerROS:
  max_vel_x: 0.7
  min_vel_x: 0.3
  max_vel_theta: 0.65
  min_vel_theta: -0.55
  min_in_place_vel_theta: 0.45

  acc_lim_theta: 0.55
  acc_lim_x: 2.5
  acc_lim_Y: 2.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.45
  yaw_goal_tolerance: 0.45
